#!/usr/bin/env python3
import re

def main():
    words = [line.strip() for line in open("/usr/share/dict/words")]
    for line in open("challenge.txt"):
        count = 0
        weight = 0.0
        rightwords = []
        test = re.sub(r'[^\w ]', "", line.strip()).split()
        while len(test[count]) < 4:
            count += 1
        if test[count] in words:
            true = 0
            for word in test:
                if word in words:
                    true += 1
            weight = true/len(test)
        if weight > 0.7:
            print(weight)
            print(test[count])
            print(line)

if __name__ == "__main__":
    main()
