#!/usr/bin/env python3

def main():
    longest = ""
    length = 0
    for line in open("/usr/share/dict/words"):
        order = garland(line.strip())
        if order > length:
            length = order
            longest = line.strip()
    print("Highest order: " + longest + ": " + str(length))

def garland(word):
    top = 0
    for i in range(len(word) -1):
        if word[:i] == word[-i:]:
            top = i
    if top >0:
        print(word +": " +str(top))
    return top

if __name__ == "__main__":
    main()
