#!/usr/bin/env python3
import itertools
def main():
    data = [line.strip() for line in open("input.txt")]
    size = float(data[0])
    num = int(data[1])
    data = data[2:]
    results = [list(filter(lambda x:x[0]<size, list(map(add, list(itertools.combinations(data, i)))))) for i in range(num)]
    results = list(filter(lambda x:len(x)>0, results))
    results = max([max(l, key=lambda x:x[0]) for l in results], key=lambda x:x[0])
    print("{0}\n{1}".format(results[0], "\n".join(results[1])))

def add(items):
    total = [0.0,[]]
    for i in items:
        total[0] += float(i)
        total[1].append(i)
    return total
if __name__ == "__main__":
    main()
