#!/usr/bin/env python3
import re
def main():
    for line in open("input.txt"):
        num = int(line.strip())
        count = 0
        while not ispalindrome(str(num)):
            num =  num + int(str(num)[::-1])
            count += 1
        print("{0} gets palndromic after {1} steps: {2}".format(line.strip(), str(count), str(num)))
def ispalindrome(string):
    if string == string[::-1]:
        return True
    return False

if __name__ == "__main__":
    main()
